sonar.projectKey=portfolio-deployment
sonar.projectName=Portfolio Deployment
sonar.projectVersion=1.0
sonar.sources=.
sonar.exclusions=vendor/**,**/*.tf,**/*.lock,**/*.java,src/**
sonar.language=php
sonar.sourceEncoding=UTF-8
