sonar.projectKey=portfolio-deployment
sonar.projectName=Portfolio Deployment
sonar.projectVersion=1.0
sonar.sources=.
sonar.exclusions=vendor/**,**/*.lock
sonar.language=php
sonar.sourceEncoding=UTF-8
